# 4. Výpočet vlastních čísel a vlastních vektorů

TODO:
- vlastní implementac QR rozkladu?
- testovat předpoklady matic
    - pro LU, QR: čtvercová
    - pro Jacobiho: čtvercová, symetrická

In [1]:
import numpy as np
from numericke_metody.eigen import *

## LR transformace (LU rozklad)

----
```python
Input: čtvercová matice A
    
1: A(0) := A, k:= 0
2: while A(k) není horní trojúhelníková:
3:      L, U := LU_rozklad(A(k))    
4:      k := k + 1
4:      A(k) := U * L
    
Output: matice A(k) s vlastními čísly na diagonále
```
----

In [3]:
A = np.array([[7,1,3,1,2],
              [2,8,6,1,5],
              [2,4,8,1,2],
             [3,4,1,7,1],
             [2,3,5,1,3]])

eigens = lr_transform(A, max_iter=30, progress=.1)


[[ 17.160932   3.80201   32.701487   1.071456   2.      ]
 [  0.         6.682669 -24.125524  -0.949161   1.028207]
 [ -0.        -0.000091   5.288074   0.116714  -1.674868]
 [ -0.         0.        -0.         2.378164  42.520854]
 [  0.         0.        -0.        -0.         1.490161]]

Vlastní čísla matice A:
        [17.1609317   6.68266901  5.2880742   2.37816444  1.49016065]


## QR transformace (QU rozklad, QR factorization)

----
```python
Input: čtvercová matice A
    
1: A(0) := A, k:= 0
2: while A(k) není horní trojúhelníková:
3:      Q, U := QU_rozklad(A(k))    
4:      k := k + 1
4:      A(k) := U * Q
    
Output: matice A(k) s vlastními čísly na diagonále
```
----

In [4]:
A = np.array([[7,1,3,1,2],
              [2,8,6,1,5],
              [2,4,8,1,2],
             [3,4,1,7,1],
             [2,3,5,1,3]])

eigens = qr_transform(A, max_iter=20, progress=.2)

[[17.160932  1.731608  2.162114  1.980017 -1.745664]
 [ 0.        6.690585 -0.546525  2.353126 -0.359025]
 [ 0.        0.016302  5.280159  2.197773 -0.577977]
 [ 0.       -0.       -0.000001  2.378207 -2.492341]
 [ 0.        0.        0.        0.000015  1.490118]]

Vlastní čísla matice A:
        [17.16093168  6.69058467  5.28015901  2.3782069   1.49011774]


## Jacobiho diagonalizace

----
```c++
Input: čtvercová matice A

01: A(0) := A, k:= 0, i:=0
02: while chyba > tolerance:
03:      if i = velikost(A) - 1: 
04:          i := 0
05:      i := i + 1
06:      j := i + 1
07:      while chyba > tolerance:
08:          A(k+1) = rotace(A(k), i, j)
09:          k := k + 1
10:          chyba = || horní_trojúhelhíková(A(k),1) ||
11:          j := j + 1

Output: matice A(k) s vlastními čísly na diagonále
```
----

In [6]:
A=np.array([[64,51,47,37,39],
            [51,130,95,56,74],
            [47,95,89,39,63],
            [37,56,39,76,33],
            [39,74,63,33,48]])

eigens = jacobi(A, eps = 1.e-8, max_iter=100, progress=.1)

[[311.466552   0.         0.        -0.         0.      ]
 [  0.        51.036309  -0.         0.        -0.      ]
 [  0.        -0.        33.211685  -0.         0.      ]
 [ -0.         0.        -0.        10.448216   0.      ]
 [  0.        -0.         0.         0.         0.837238]]

Počet iterací: 31
Vlastní čísla matice A:
        [311.46655191  51.03630923  33.21168474  10.44821577   0.83723836]


<br>
<br>
__Jacobiho diagonalizace s volbou maximalního prvku v absolutní hodnotě pro získání matice rotace__

----
```c++
Input: čtvercová matice A

1: A(0) := A, k := 0
2: while chyba > tolerance:
3:      i, j := index_největšího_prvku (horní_trojúhelníková(A(k)))  
4:      A(k+1) := rotace(A(k), i, j)
5:      k := k + 1
6:      chyba := || horní_trojúhelhíková(A(k),1) ||

Output: matice A(k) s vlastními čísly na diagonále
```
----

In [7]:
A=np.array([[64,51,47,37,39],
            [51,130,95,56,74],
            [47,95,89,39,63],
            [37,56,39,76,33],
            [39,74,63,33,48]])

eigens = jacobi_max(A, eps = 1.e-8, max_iter=100, progress=.1)

[[311.466552   0.        -0.        -0.         0.      ]
 [  0.        51.036309  -0.         0.         0.      ]
 [ -0.        -0.        33.211685   0.        -0.      ]
 [ -0.         0.         0.        10.448216   0.      ]
 [  0.         0.        -0.         0.         0.837238]]

Počet iterací: 29
Vlastní čísla matice A:
        [311.46655191  51.03630923  33.21168474  10.44821577   0.83723836]
